"""add payment method to payment intents

Revision ID: 14a44074841a
Revises: f54c845c0ceb
Create Date: 2026-07-15 19:35:12.089364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a44074841a'
down_revision: Union[str, Sequence[str], None] = 'f54c845c0ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intents', sa.Column('payment_method_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'payment_intents', 'payment_methods', ['payment_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_intents', type_='foreignkey')
    op.drop_column('payment_intents', 'payment_method_id')
    # ### end Alembic commands ###
