"""create merchant API credentials table

Revision ID: 8bc33201ce7d
Revises: 357a7d9c60de
Create Date: 2026-07-14 20:10:29.208307

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bc33201ce7d"
down_revision: str | Sequence[str] | None = "357a7d9c60de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_api_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("key_prefix", sa.String(length=32), nullable=False),
        sa.Column("secret_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked', 'expired')",
            name="ck_merchant_api_credentials_status",
        ),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchant_api_credentials_key_prefix"),
        "merchant_api_credentials",
        ["key_prefix"],
        unique=True,
    )
    op.create_index(
        op.f("ix_merchant_api_credentials_merchant_id"),
        "merchant_api_credentials",
        ["merchant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_merchant_api_credentials_merchant_id"),
        table_name="merchant_api_credentials",
    )
    op.drop_index(
        op.f("ix_merchant_api_credentials_key_prefix"),
        table_name="merchant_api_credentials",
    )
    op.drop_table("merchant_api_credentials")
    # ### end Alembic commands ###
