"""Add payment intent error code

Revision ID: b30230fa65ab
Revises: f10ede1504c7
Create Date: 2026-07-15 00:55:39.868164

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b30230fa65ab"
down_revision: str | Sequence[str] | None = "f10ede1504c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_intents",
        sa.Column("last_error_code", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_intents", "last_error_code")
    # ### end Alembic commands ###
