"""create payment methods table

Revision ID: f54c845c0ceb
Revises: b30230fa65ab
Create Date: 2026-07-15 14:50:13.231524

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f54c845c0ceb"
down_revision: str | Sequence[str] | None = "b30230fa65ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("card_brand", sa.String(length=30), nullable=False),
        sa.Column("card_last4", sa.String(length=4), nullable=False),
        sa.Column("card_exp_month", sa.Integer(), nullable=False),
        sa.Column("card_exp_year", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default="active", nullable=False
        ),
        sa.Column(
            "test_scenario",
            sa.String(length=50),
            server_default="success",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "card_last4 ~ '^[0-9]{4}$'", name="ck_payment_methods_card_last4_format"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')", name="ck_payment_methods_status"
        ),
        sa.CheckConstraint(
            "test_scenario IN ('success', 'card_declined')",
            name="ck_payment_methods_test_scenario",
        ),
        sa.CheckConstraint("type IN ('card')", name="ck_payment_methods_type"),
        sa.CheckConstraint(
            "card_exp_month BETWEEN 1 AND 12", name="ck_payment_methods_card_exp_month"
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
